---
# Playbook for killing processes on the hosts on the testbed.
#
# WARNING: This playbook will:
#                   - Kill any tracereplay programs on the load generator.
#                   - Kill MOSP and Nmeta2DPAE on the DPAE host.
#                   - Kill ryu-manager on the controller.

- hosts: servers
  tasks:
    - name: Kill any pcounter programs that are currently running.
      command: "sudo pkill -f pcounter"
      ignore_errors: True

- hosts: load-generators
  tasks:
    - name: Kill all tracereplay programs that are currently running.
      command: "sudo pkill -f tracereplay"
      ignore_errors: True

- hosts: dpae
  tasks:
    - name: Kill any MOSP programs that are currently running.
      command: "pkill -f mosp"
      ignore_errors: True
    - name: Kill any DPAE programs that are currently running.
      command: "sudo pkill -f nmeta2dpae.py"
      ignore_errors: True

- hosts: controllers
  tasks:
    - name: Kill all existing Ryu processes.
      command: "pkill -f ryu-manager"
      ignore_errors: True
