---
# Playbook for starting MOSP and the Nmeta2 DPAE application on the DPAE.

- hosts: dpae
  tasks:
    - name: Run MOSP for up to 25 hours.
      command: "nohup python mosp.py --output-file {{ mosp_outfile }}_mosp.csv --output-path /home/dp1/Documents/mosp_results/ -i 1 &"
      args:
        chdir: ~/mosp
      async: 90000
      poll: 0

    - name: Pause after starting MOSP.
      pause: seconds=10

    - name: Run the Nmeta2 DPAE application for up to  25 hours.
      shell: "nohup sudo /home/dp1/nmeta2dpae/nmeta2dpae.py >/dev/null 2>&1 &"
      async: 90000
      poll: 0
